name: Branching workflow

on:
  push:
    branches: [dev/staging]

jobs:
  merge:
    name: Sync dev/features branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - run: |
          git checkout dev/features
          git merge dev
          git push origin features
